### PR TITLE
Fix compilation errors and warnings for UE 4.26

### PR DESCRIPTION
**Pull request by ufna**
Fixes issues for UE 4.26. 

Thought it's a right branch.

### CODE REVIEW

**Comment by fmod-derek** [comment]
Unfortunately just fixing the compilation errors and warnings isn't enough to get the integration working with UE4 4.26, these changes also can't be made to the 4.25+ branch because they will break it. Our February release will include an updated version of the integration for UE4 4.26 which will also be pushed to a new branch on GitHub.
